### DISCUSSION TITLE
Telegraf / Grafana Integration

### DISCUSSION THREAD

**Discussion by cyberthom42** [cyberthom42/vaillant-arotherm-plus#18] [Q&A]
Ich versuche schon seit einer Weile eine vernünftige Telegraf Integration hin zubekommen. Leider bisher ohne finalen Erfolg. 
Das Problem ist, dass einige Elemente string sind und einige int und float.
Was bisher funktioniert:
1.) Data_format "value"
Topic mit %field , also ..../%circuit/%name/%field
Das klappt, allerdings klappt das pivot noch nicht für Elemente sie mehrere Fields haben (z.b. Status01). Ich habe noch nicht probiert string von float zu unterscheiden, ich würde versuchen im Value Feld die Anführungszeichen zu erkennen. 
2.) Data_type json
Hier dann ohne %field im topic. Geht auch, allerdings habe ich hier das Problem ein pivot hin zu bekommen. Problem mit string und float ist das gleiche

Man könnte die Field Namen in den csv einheitlich benennen und z.b. "string_onoff" oder "float_temp". Damit könnte mann dann evtl einem einfachen topic Filter nutzen.

Wie macht ihr das?

**Comment by oysteing** [comment]
Multi-Field-Topics (Status01, SetMode) habe ich in Telegraf explizit konfiguriert, oder gar nicht verwendet.

Alle Einzelwerte als JSON und Strings als `json_string_fields`:
```
[[inputs.mqtt_consumer]]
  topics = [
    "ebusd/hmu/+",
    "ebusd/ctlv2/+"
  ]
  name_override = "ebusd"

  data_format = "json"
  json_string_fields = ["off", "on", "heating", "dhw"]

  [[inputs.mqtt_consumer.topic_parsing]]
    topic = "ebusd/+/+"
    tags = "_/circuit/field"
```

**Reply by cyberthom42** [reply]
Wenn ich die Config richtig lese, werden doch die Multi-Field Topics mit interpretiert... 

Bei mir sieht das z.B. dann so aus:
`ebusd/vwzio/Status01 {
     "0": {"name": "temp1", "value": 33.0},
     "1": {"name": "temp1", "value": null},
     "2": {"name": "pumpstate", "value": "off"}}
`


Wie sieht deine MQTT ebusd Config (EBUSD_OPTS) hierzu aus? 
Meine sieht so aus:
`EBUSD_OPTS="  .....  --mqtthost=xx.xx.xx.xx --mqttport=1883 --mqttjson"`

**Reply by oysteing** [reply]
So sieht es bei mir aus (docker-compose.yaml):
```
    environment:
      EBUSD_CONFIGPATH: /ebusd-configuration
      EBUSD_DEVICE: "ens:/dev/ttyACM0"
      EBUSD_MQTTHOST: mqtt
      EBUSD_MQTTPORT: 1883
      EBUSD_MQTTUSER: ebusd
      EBUSD_MQTTPASS: ####
      EBUSD_MQTTJSON: short
      EBUSD_MQTTCHANGES: true
```

Habt ihr mit "--mqttjson" statt "--mqttjson=short" bessere Erfahrungen? Eventuell "--mqttverbose"?
